### PR TITLE
200 file object fixes

### PR DESCRIPTION
**Pull request by JRCockrum**
The file object was renamed to File Access. I added some more error checking and types to all the variables

### CODE REVIEW

**Comment by harperstoeckle** [comment]
This needs to be merged into `dev` instead of `main`.

**Review by harperstoeckle — CHANGES_REQUESTED** [review]
This needs to be merged into `dev` instead of `main`.

**Comment by jakobrosencu** [comment]
Agree with Harper, will also probably become quite a bit easier to parse and review.

**Comment by EveDiby** [comment]
I agree with Harper and Jake that this should be merged into the dev branch. From what I understand, the updated code looks correct.

**Review by harperstoeckle — APPROVED** [review]

**Review by jakobrosencu — APPROVED** [review]

**Pull request merged**
