### PR TITLE
188 - Camera2D

### PR DESCRIPTION
**Pull request by AlexPhilipsen**

### CODE REVIEW

**Review by Drock54651 — APPROVED** [review]

**Review by jakobrosencu — APPROVED** [review]

**Review by maoc1414 — APPROVED** [review]

**Comment by JRCockrum** [comment]
Looks good to me, before you merge just make sure to add types to all the variables that you can

**Review by JRCockrum — CHANGES_REQUESTED** [review]
Looks good to me, just make sure to add types to all the variables you can before merging

**Comment by AlexPhilipsen** [comment]
Good catch on the types, I should be finished adding them to the file.

**Review by JRCockrum — APPROVED** [review]
Looks good

**Pull request merged**
